trigger: 
 - main

variables:
   imageName: 'pipelines-azwebapp-docker'

jobs:
- job: Build_AzWebApp

  pool:
    vmImage: 'ubuntu-latest'

  steps: 
  - task: GoTool@0
    inputs:
      version: '1.13.5'
  - task: Go@0
    inputs:
      command: 'get'
      arguments: '-d'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: Go@0
    inputs:
      command: 'build'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: CopyFiles@2
    inputs:
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: drop
  - task: Go@0
    inputs:
      command: 'build'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: Go@0
    inputs:
      command: 'test'
      arguments: '-v'
      workingDirectory: '$(System.DefaultWorkingDirectory)'


- task: Docker@2
  displayName: Build an image
  input:
    repository: $(imageName)
    command: build
    Dockerfile: Docker/Dockerfile

#displayName: "login to Docker Hub"
#inputs:
#command: login
###containerRegistry: 'Docker Hub'
##- task: Docker@2
#displayName: 'Build and Push Image'
#inputs:
#command: buildAndPush
#repository: fz96tw/azwebapp/Docker
#tags: 
#latest
#$(Build.BuildId)
